minimum_pre_commit_version: 2.15.0
exclude: ^\.(html|csv|svg)$

repos:
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
    - id: absolufy-imports
      files: ^comps/

- repo: https://github.com/python/black
  rev: 22.6.0
  hooks:
    - id: black

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
  - id: codespell
    types_or: [python, rst, markdown]
    args: ["-w"]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

# - repo: https://github.com/PyCQA/pylint
#   rev: v2.15.3
#   hooks:
#   - id: pylint
#     args:
#       [
#         "-rn", # Only display messages
#         "-sn", # Don't display the score
#         "--rcfile=pylintrc", # Link to your config file
#         "--load-plugins=pylint.extensions.docparams", # Load an extension
#       ]

# - repo: https://github.com/jendrikseipp/vulture
#   rev: 'v2.5'
#   hooks:
#     - id: vulture

- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v0.6.1
  hooks:
  - id: sphinx-lint

