name: comps

channels:
  - conda-forge
  - nodefaults

dependencies:
  # Core dependencies for calculation and visualization
  - numpy>=1.21
  - pandas>=1.3
  - pandas-stubs>=1.2
  - plotly>=5.0
  - pyarrow>=6.0
  - pyspark-stubs>=3.0
  - pyspark>=3.0
  - python>=3.9
  - scikit-learn>=1.1
  - scipy>=1.8
  - typing_extensions>=4.0
  # Documentation dependencies pinned for build stability
  - conda-build=3.21.8
  - ipython
  - mypy
  - pydata-sphinx-theme=0.8.1
  - pytest-cov
  - pytest-sugar
  - pytest
  - sphinx-design=0.1.0
  - sphinx=4.5.0
  - types-pyyaml
