name: comps

channels:
  - conda-forge
  - nodefaults

dependencies:
  # Core dependencies for calculation and visualization
  - dask>=2021.6.0
  - grpcio>=1.43  # Because pip version doesn't support Apple Silicon
  - numpy>=1.21
  - plotly>=5.0
  - python=3.10
  - scikit-learn>=1.1
  - scipy>=1.8
  - typing_extensions=4.*
  # Development dependencies pinned for testing and documentation stability
  - conda-build=3.21.8
  - ipython=8.2.0
  - mypy=0.940
  - pydata-sphinx-theme=0.8.1
  - pyspark=3.3.0
  - pytest-cov=3.0.0
  - pytest-sugar=0.9.4
  - pytest=6.2.5
  - sphinx-design=0.1.0
  - sphinx=4.5.0
  - types-pyyaml=6.0.7

  - pip:
    # Required for extened for datahub
    - ray>=2.0.0
    - ray[data]
