name: comps
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core dependencies for calculation and visualization
  - python=3.9
  - scikit-learn=1.*
  - scipy>=1.8.*
  - matplotlib=3.3.*
  - typing_extensions=4.*
  # Optional or extened dependencies for xfmr dataframe interaction package
  - pandas>=1.3.*
  # polars>=0.13.*
  - pyspark>=3.1.*
  - vaex-core>=4.6.*
  # Development dependencies pinned for testing and documentation stability
  - conda-build=3.21.8
  - pre-commit=2.19.0
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - pytest-sugar=0.9.4
  # bandit=1.7.4
  - black=22.3.0
  - blackdoc=0.3.4
  - ipython=8.2.0
  - isort=5.10.1
  - mypy=0.940
  - pylint=2.13.8
  - ghp-import=2.0.2
  - flake8=4.0.1
  - sphinx=4.5.0
  - pydata-sphinx-theme=0.8.1
  - sphinx-design=0.1.0
  - types-pyyaml=6.0.7
  - types-setuptools=57.4.10
  - pip:
    - bandit==1.7.4    # 1.7.4 used in poetry/pip builds not available from conda-forge
    - polars>=0.13.*  # Polars not available from conda-forge
