package:
  name: imagesize
  version: '0.0.1' 

source:
  url: https://github.com/cksisu/comps

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - numpy>=1.21
    - pandas>=1.3
    - plotly>=5.0
    - pyarrow>=6.0
    - pyspark>3.0
    - python>=3.9
    - scikit-learn>=1.1
    - scipy>=1.8
    - typing_extensions>=4.0

test:
  imports:
    - imagesize

about:
  home: https://github.com/cksisu/comps
  license: BSD3
  summary: 'Comparison and causal inference'
  description: >
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
